version: '3'
services:
    casa-do-codigo:
        image: mysql:latest
        container_name: casa-do-codigo
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=my-user
            - MYSQL_PASSWORD=123
            - MYSQL_DATABASE=casa-do-codigo